### ISSUE TITLE
Error to start container

### ISSUE THREAD

**Issue by polotto** [pascalgrimaud/docker-jboss-as#3]
I follow the build steps, but I found this error:

```
$ docker run -p 8080:8080 -p 9990:9990 pascalgrimaud/jboss-as:7.1.1
Starting container : JBoss AS 7.1.1
Initializing the admin user password...
Exception in thread "main" javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory could not be instantiated: java.lang.NullPointerException
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:132)
	at jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:232)
	at jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:78)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:319)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:254)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:467)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:474)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:357)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:292)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.<init>(XMLSchemaFactory.java:96)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:238)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:145)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:202)
	at __redirected.__SchemaFactory.<clinit>(__SchemaFactory.java:66)
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:88)
	at org.jboss.modules.Module$1.run(Module.java:85)
	at org.jboss.modules.Module$1.run(Module.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.Module.<clinit>(Module.java:72)
	at org.jboss.modules.Main.main(Main.java:255)
Caused by: java.lang.NullPointerException
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:94)
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:87)
	at __redirected.__SAXParserFactory.<init>(__SAXParserFactory.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:179)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:147)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:219)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:126)
	... 19 more
Initializing the admin user password : ok

######################################################################
You can now configure to this JBoss server using:

    Username : admin
    Password : Y2JhOGFmYzMwNzM5

######################################################################

=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss-as-7.1.1.Final

  JAVA: /usr/lib/jvm/java-7-openjdk-amd64/bin/java

  JAVA_OPTS:  -server -XX:+UseCompressedOops -XX:+TieredCompilation -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.server.default.config=standalone.xml

=========================================================================

Exception in thread "main" javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory could not be instantiated: java.lang.NullPointerException
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:132)
	at jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:232)
	at jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:78)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:319)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:254)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:467)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:474)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:357)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:292)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.<init>(XMLSchemaFactory.java:96)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:238)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:145)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:202)
	at __redirected.__SchemaFactory.<clinit>(__SchemaFactory.java:66)
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:88)
	at org.jboss.modules.Module$1.run(Module.java:85)
	at org.jboss.modules.Module$1.run(Module.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.Module.<clinit>(Module.java:72)
	at org.jboss.modules.Main.main(Main.java:255)
Caused by: java.lang.NullPointerException
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:94)
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:87)
	at __redirected.__SAXParserFactory.<init>(__SAXParserFactory.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:179)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:147)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:219)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:126)
	... 19 more
```

I'm using Ubuntu 19.10 and docker 19.03.2.

Do you know if this can be some dependency problem in the Dockerfile?

**Comment by aadimurthy** [comment]
This could be fixed by:
1) Download `jboss-modules-1.1.5.ga.jar` from [here](http://www.java2s.com/Code/Jar/j/Downloadjbossmodules115gajar.htm) 
2) Rename it to `jboss-modules.jar`
3) Replace it with the original jar present in JBoss home directory inside failed to start docker
Command to copy from local to inside docker 
 `docker cp  jboss-modules.jar <container ID>:/opt/jboss-as-7.1.1.Final/jboss-modules.jar`
